version: '3.8'
services:
  app:
    restart: always
    build: .
    volumes:
      - ./app:/home/app/
      - ./logs/gunicorn/:/home/logs/gunicorn/
      - ./app/media:/home/app/media/
      - ./app/static:/home/app/static/
    command: ["sh", "./start.sh"]
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./app/media:/home/app/media/
      - ./app/static:/home/app/static/
    networks:
      - nginx_network
    depends_on:
      - app
  db:
    image: postgres:alpine
    restart: always
    networks:
      - db_network
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge